version: '3.9'

services:
  car_rent_db:
    container_name: Car_Rent_DB
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Car_Rent_DB

    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}