spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/Car_Rent_DB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect